"""LoRA adapter metadata, compatibility, and lifecycle services."""

from tiny_qwen_coder.adapters.all_linear import (
    AllLinearCategorySummary,
    AllLinearValidationError,
    AllLinearValidationReport,
    all_linear_report_json,
    all_linear_report_text,
    build_all_linear_validation_report,
    validate_all_linear_main,
    validate_literal_all_linear,
)
from tiny_qwen_coder.adapters.manifest import (
    AdapterBaseIdentity,
    AdapterLoraMetadata,
    AdapterManifest,
    AdapterManifestError,
    AdapterTokenizerIdentity,
    AdapterTrainingProvenance,
    AdapterTrainingSummary,
    ChatTemplateIdentity,
    DatasetManifestReference,
    TrainingComponentSettings,
    TrainingSetting,
    ValidationMetric,
    adapter_manifest_json,
    load_adapter_manifest,
    parse_adapter_manifest,
)
from tiny_qwen_coder.adapters.targets import (
    PeftTargetDiscoveryReport,
    TargetCategorySummary,
    TargetDiscoveryError,
    TargetModuleRecord,
    discover_peft_targets,
    discover_peft_targets_main,
    peft_target_report_json,
    peft_target_report_text,
)

__all__ = [
    "AdapterBaseIdentity",
    "AdapterLoraMetadata",
    "AdapterManifest",
    "AdapterManifestError",
    "AdapterTokenizerIdentity",
    "AdapterTrainingProvenance",
    "AdapterTrainingSummary",
    "AllLinearCategorySummary",
    "AllLinearValidationError",
    "AllLinearValidationReport",
    "ChatTemplateIdentity",
    "DatasetManifestReference",
    "PeftTargetDiscoveryReport",
    "TargetCategorySummary",
    "TargetDiscoveryError",
    "TargetModuleRecord",
    "TrainingComponentSettings",
    "TrainingSetting",
    "ValidationMetric",
    "adapter_manifest_json",
    "all_linear_report_json",
    "all_linear_report_text",
    "build_all_linear_validation_report",
    "discover_peft_targets",
    "discover_peft_targets_main",
    "load_adapter_manifest",
    "parse_adapter_manifest",
    "peft_target_report_json",
    "peft_target_report_text",
    "validate_all_linear_main",
    "validate_literal_all_linear",
]
